# ==================================================================
# ROS2 to Mass AMR Interoperability Standard node configuration file
# ==================================================================
#
# Parameters that are used to configure ROS2 node for connecting to Mass compatible servers.
# The `server` section expects a string with a WebSocket server URI, while the `mapping` section
# contains a list of paramaters for configuring the ROS2 node. Mandatory parameters are `uuid`,
# `manufacturerName`, `robotModel`, `robotSerialNumber` and `baseRobotEnvelope` (see full spec
# https://github.com/MassRobotics-AMR/AMR_Interop_Standard/blob/main/AMR_Interop_Standard.json).
# 
# In addition to static values i.e. strings or objects, the `mapping` section supports a variety of
# sources from where the parameter value can be obtained: `envVar`, `rosTopic` and `rosParameter`.

config:
  server: "wss://localhost:3000"
  mapping:
    # Identity
    uuid:
      valueFrom:
        envVar: MY_UUID
    manufacturerName: Spoonlift
    robotModel: "spoony1.0"
    robotSerialNumber: "2172837"
    baseRobotEnvelope:
        x: 2
        y: 1
        z: 3
    maxSpeed: 2.5
    maxRunTime: 8
    emergencyContactInformation: "555-5555"
    chargerType: "24V plus"
    supportVendorName: "We-B-Robots"
    supportVendorContactInformation: "support@we-b-robots.com"
    productDocumentation: "https://spoon.lift/support/docs/spoony1.0"
    thumbnailImage: "https://spoon.lift/media/spoony1.0.png"
    cargoType: "Anything solid or liquid"
    cargoMaxVolume:
      value:
        x: 2
        y: 2
        z: 1
    cargoMaxWeight: 4000
    # Status
    operationalState:
      valueFrom:
        rosTopic: /we_b_robots/mode
        # std_msgs/String
    pose:
      valueFrom:
        rosTopic: /magic_nav/current_pose
        # geometry_msgs/PoseStamped
    velocity:
      valueFrom:
        rosTopic: /good_sensors/vel
        # geometry_msgs/TwistStamped
    batteryPercentage:
      valueFrom:
        rosTopic: /good_sensors/bat
        # std_msgs/Float32
    remainingRunTime:
      valueFrom:
        rosTopic: /we_b_robots/remaining_time
        # std_msgs/Float32
    loadPercentageStillAvailable:
      valueFrom:
        rosTopic: /spoonlift/available_capacity_percentage
        # std_msgs/Float32
    errorCodes: TBD / Juli / Flor
    destinations:
      valueFrom:
        rosTopic: /we_b_robots/destinations
        # nav_msgs/Path
    path:
      valueFrom:
        rosTopic: /magic_nav/path
      # nav_msgs/Path
    rosFrameToPlanarDatumUUID:
      # required since Mass expects frames to be referenced using uuids
      map: "096522ad-61fa-4796-9b31-e35b0f8d0b26"
      floor1: "096522ad-61fa-4796-9b31-e35b0f8d0b26"
      floor2: "6ec7a6d0-21a9-4f04-b680-e7c640a0687e"
