name: Lint ROS2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    # branches:
    #   - master

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: ubuntu:focal
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ros-tooling/setup-ros@0.2.1
      with:
        required-ros-distributions: foxy
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: ros2_to_mass_amr_interop
        target-ros2-distro: foxy
